### ISSUE TITLE
Permissions issue in 4.0 beta 2

### ISSUE THREAD

**Issue by daltonrooney** [venveo/craft-redirect#52]
Somewhere between beta 1 and beta 2 we started noticing a permissions issue when trying to create a new redirect:

```
2022-08-22 16:44:30 [web.ERROR] [yii\web\HttpException:403] yii\web\ForbiddenHttpException: User not authorized to create this element. in /home/raygun/webapps/dev/craft/vendor/craftcms/cms/src/controllers/ElementsController.php:188
Stack trace:
#0 [internal function]: craft\controllers\ElementsController->actionCreate()
#1 /home/raygun/webapps/dev/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /home/raygun/webapps/dev/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#3 /home/raygun/webapps/dev/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#4 /home/raygun/webapps/dev/craft/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction()
#5 /home/raygun/webapps/dev/craft/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction()
#6 /home/raygun/webapps/dev/craft/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest()
#7 /home/raygun/webapps/dev/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#8 /home/raygun/webapps/dev/public/index.php(26): yii\base\Application->run()
#9 {main} {"memory":4585008,"exception":"[object] (yii\\web\\ForbiddenHttpException(code: 0): User not authorized to create this element. at /home/raygun/webapps/dev/craft/vendor/craftcms/cms/src/controllers/ElementsController.php:188)"} 
2022-08-22 16:44:30 [web.INFO] [application] Request context:
$_GET = [
    'p' => 'admin/actions/elements/create'
    'v' => '1661186670542'
]
```

Reverting back to beta 1 seems to have fixed it for now. Let me know if we can provide any further info.

**Comment by Mosnar** [comment]
Thanks, I'll take a look ASAP!

**Comment by Mosnar** [comment]
Fixed in beta 3 and beta 4
