### ISSUE TITLE
Failing search index jobs on Linux

### ISSUE THREAD

**Issue by gglnx** [venveo/craft-redirect#59]
Search index jobs for redirect element fail currently:

```
> yii\base\InvalidArgumentException: The file or directory to be published does not exist: /.../vendor/bower/jquery/dist
Stack trace:
#0 /.../vendor/yiisoft/yii2/web/AssetBundle.php(181): yii\web\AssetManager->publish()
#1 /.../vendor/yiisoft/yii2/web/AssetManager.php(294): yii\web\AssetBundle->publish()
#2 /.../vendor/yiisoft/yii2/web/AssetManager.php(265): yii\web\AssetManager->loadBundle()
#3 /.../vendor/yiisoft/yii2/web/View.php(294): yii\web\AssetManager->getBundle()
#4 /.../vendor/yiisoft/yii2/web/View.php(299): yii\web\View->registerAssetBundle()
#5 /.../vendor/yiisoft/yii2/web/View.php(299): yii\web\View->registerAssetBundle()
#6 /.../vendor/yiisoft/yii2/web/View.php(299): yii\web\View->registerAssetBundle()
#7 /.../vendor/venveo/craft-redirect/src/fieldlayoutelements/RedirectSourceField.php(20): yii\web\View->registerAssetBundle()
#8 /.../vendor/yiisoft/yii2/base/BaseObject.php(109): venveo\redirect\fieldlayoutelements\RedirectSourceField->init()
#9 /.../vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct()
#10 /.../vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(59): craft\base\Model->__construct()
#11 /.../vendor/venveo/craft-redirect/src/elements/Redirect.php(408): craft\fieldlayoutelements\BaseField->__construct()
#12 /.../vendor/craftcms/cms/src/base/Element.php(4926): venveo\redirect\elements\Redirect->getFieldLayout()
#13 /.../vendor/craftcms/cms/src/base/Element.php(2038): craft\base\Element->fieldByHandle()
#14 /.../vendor/venveo/craft-redirect/src/elements/Redirect.php(893): craft\base\Element->__get()
#15 /.../vendor/venveo/craft-redirect/src/elements/Redirect.php(791): venveo\redirect\elements\Redirect->formatUrl()
#16 /.../vendor/yiisoft/yii2/base/Component.php(180): venveo\redirect\elements\Redirect->setSourceUrl()
#17 /.../vendor/craftcms/cms/src/base/Element.php(2061): yii\base\Component->__set()
#18 /.../vendor/yiisoft/yii2/BaseYii.php(558): craft\base\Element->__set()
#19 /.../vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure()
#20 /.../vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct()
#21 /.../vendor/craftcms/cms/src/base/Element.php(1963): craft\base\Model->__construct()
#22 /.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1863): craft\base\Element->__construct()
#23 /.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(2949): craft\elements\db\ElementQuery->createElement()
#24 /.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1453): craft\elements\db\ElementQuery->_createElements()
#25 /.../vendor/yiisoft/yii2/db/Query.php(251): craft\elements\db\ElementQuery->populate()
#26 /.../vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->all()
#27 /.../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1492): craft\db\Query->all()
#28 /.../vendor/craftcms/cms/src/queue/jobs/UpdateSearchIndex.php(59): craft\elements\db\ElementQuery->all()
#29 /.../vendor/yiisoft/yii2-queue/src/Queue.php(246): craft\queue\jobs\UpdateSearchIndex->execute()
#30 /.../vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage()
#31 /.../vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute()
#32 [internal function]: yii\queue\cli\Command->actionExec()
#33 /.../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#34 /.../vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#35 /.../vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#36 /.../vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#37 /.../vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#38 /.../vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction()
#39 /.../vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#40 /.../vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest()
#41 /.../vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#42 /.../craft(17): yii\base\Application->run()
#43 {main}
```

I think because `RedirectSourceField` registers it's asset bundle on `init` and not on `inputHtml`.

* Craft 4.3.8
* Plugin 4.0.0-beta.3

**Comment by Mosnar** [comment]
Tagged 4.0.0-beta.4
